parameter1/industrial-media-websites

sites/impomag/server/templates/index.marko, sites/inddist/server/templates/index.marko
=> Home page updates for ID, IMPO

sites/inddist/config/navigation.js
=> Rename Workforce Development to Workforce

packages/common/scss/core.scss, sites/foodmanufacturing/server/styles/index.scss, sites/impomag/server/styles/index.scss, sites/inddist/server/styles/index.scss, sites/manufacturing/server/styles/index.scss, sites/mbtmag/server/styles/index.scss
=> add core css override for content h3 header margin

sites/manufacturing/config/navigation.js, sites/manufacturing/server/components/flows/content-hero.marko, sites/manufacturing/server/components/flows/marko.json, sites/manufacturing/server/templates/index.marko
=> Remove magazine from nav & add list header to hero block

sites/inddist/config/navigation.js
=> Add “Big 50” to the secondary nav and menu

sites/inddist/config/navigation.js
=> Cram Big 50 into the primary nav

packages/common/package.json, sites/foodmanufacturing.com/browser/index.js, sites/foodmanufacturing.com/package.json, sites/foodmanufacturing.com/server/graphql/fragments/content-page.js, sites/foodmanufacturing.com/server/styles/index.scss, sites/foodmanufacturing.com/server/templates/content/index.marko, sites/impomag.com/browser/index.js, sites/impomag.com/package.json, sites/impomag.com/server/graphql/fragments/content-page.js, sites/impomag.com/server/styles/index.scss, sites/impomag.com/server/templates/content/index.marko, sites/inddist.com/browser/index.js, sites/inddist.com/package.json, sites/inddist.com/server/graphql/fragments/content-page.js, sites/inddist.com/server/styles/index.scss, sites/inddist.com/server/templates/content/index.marko, sites/manufacturing.net/browser/index.js, sites/manufacturing.net/package.json, sites/manufacturing.net/server/graphql/fragments/content-page.js, sites/manufacturing.net/server/styles/index.scss, sites/manufacturing.net/server/templates/content/index.marko, sites/mbtmag.com/browser/index.js, sites/mbtmag.com/package.json, sites/mbtmag.com/server/graphql/fragments/content-page.js, sites/mbtmag.com/server/styles/index.scss, sites/mbtmag.com/server/templates/content/index.marko, yarn.lock
Will display photoswipe lightbox on all content pages except contacts.
[Original Jira Request](https://southcomm.atlassian.net/browse/BCMS-183?atlOrigin=eyJpIjoiNTlkZjQyMzM2ZDAzNDBiZmE5ZGYxMDMwMmU5YTU4ZTQiLCJwIjoiaiJ9)
=> Add gallery/lightbox functionality to content pages

sites/foodmanufacturing.com/server/routes/dynamic-page.js, sites/impomag.com/server/routes/dynamic-page.js, sites/inddist.com/server/routes/dynamic-page.js, sites/manufacturing.net/server/routes/dynamic-page.js, sites/mbtmag.com/server/routes/dynamic-page.js
Previously it would only match alpha numerical characters and -
=> Change page alias lookup to support all characters

.travis.yml, docker-compose.yml, package.json, services/marketing-cloud/data-extensions/refresh.js, services/marketing-cloud/env.js, services/marketing-cloud/newrelic.js, services/marketing-cloud/nr.js, services/marketing-cloud/package.json, services/marketing-cloud/rest.js, services/marketing-cloud/soap.js, yarn.lock
Includes a script to refresh marketing cloud data extensions.
The production container must specify the working directory, entrypoint and env values as defined by the `mc-refresh-data-extensions` service in `docker-compose.yml`.
=> Create Marketing Cloud service

packages/shared/browser/index.js, packages/shared/components/content-page/comments.marko, packages/shared/components/content-page/gate.marko, packages/shared/components/content-page/marko.json, packages/shared/components/document.marko, packages/shared/components/marko.json, packages/shared/graphql/fragments/content-page.js, packages/shared/package.json, packages/shared/routes/user.js, packages/shared/scss/components/_content-page.scss, packages/shared/scss/components/_identity-x.scss, packages/shared/scss/core.scss, packages/shared/start-server.js, packages/shared/templates/content/index.marko, packages/shared/templates/user/authenticate.marko, packages/shared/templates/user/login.marko, packages/shared/templates/user/logout.marko, packages/shared/templates/user/profile.marko, packages/shared/templates/user/register.marko, packages/shared/utils/get-content-preview.js, sites/cannabisequipmentnews.com/config/site.js, sites/designdevelopmenttoday.com/config/site.js, sites/foodmanufacturing.com/config/site.js, sites/ien.com/config/site.js, sites/impomag.com/config/site.js, sites/inddist.com/config/site.js, sites/manufacturing.net/config/site.js, sites/mbtmag.com/config/site.js, yarn.lock
Will only apply to sites using the shared package
Comment block:
Content gate:
=> Integrate IdentityX login/gating/comments for all sites

docker-compose.yml, packages/marketing-cloud/data-extensions/opt-in-manager.js, packages/marketing-cloud/env.js, packages/marketing-cloud/package.json, packages/marketing-cloud/rest.js, packages/marketing-cloud/soap.js, packages/shared/browser/.eslintrc.js, packages/shared/browser/index.js, packages/shared/browser/newsletter-signup/index.vue, packages/shared/graphql/queries/newsletter-signup.js, packages/shared/package.json, packages/shared/routes/newsletter-signup.js, packages/shared/start-server.js, packages/shared/templates/newsletter-signup.marko, services/marketing-cloud/package.json, sites/cannabisequipmentnews.com/config/navigation.js, sites/cannabisequipmentnews.com/server/styles/index.scss, sites/designdevelopmenttoday.com/config/navigation.js, sites/ien.com/config/navigation.js, yarn.lock
Adds support for adding/removing subscribers to Marketing Cloud (ExactTarget) data extensions.
This is only supported via the `shared` package and has yet to be configured for sites other than IEN, DDT, and CEN.
=> Create newsletter signup pages

sites/designdevelopmenttoday.com/config/navigation.js, sites/designdevelopmenttoday.com/server/styles/index.scss
- Drop "Industries"
- Arrange in alpha order: "Aerospace", "Automotive", "Manufacturing", "Medical & Military"
=> Add industry sub-sections to primary nav

sites/ien.com/config/navigation.js
- Add "Software" and "Made in America"
- Drop "Advanced MFG" and "Food & Bev"
=> Move "Software" and "Made in America" to primary nav

packages/shared/graphql/queries/newsletter-signup.js, packages/shared/templates/newsletter-signup.marko
Requires base-cms/base-cms#391
=> Flip order of Update & Today on the subscription page

packages/shared/utils/sort-nav-items.js, sites/cannabisequipmentnews.com/config/navigation.js, sites/designdevelopmenttoday.com/config/navigation.js, sites/foodmanufacturing.com/config/navigation.js, sites/ien.com/config/navigation.js, sites/impomag.com/config/navigation.js, sites/inddist.com/config/navigation.js, sites/manufacturing.net/config/navigation.js, sites/mbtmag.com/config/navigation.js
In addition, add social icons to tertiary nav on Mnet and MBT.
=> Alpha sort all primary/menu nav items

packages/shared/templates/content/index.marko
https://staging.ien.com/finishing-world/power-tools/company/21119960/mirka
=> Adjust skip on company and contact load more

sites/designdevelopmenttoday.com/config/navigation.js
=> Remove resources from DDT menu

packages/shared/graphql/fragments/content-page.js
https://app.everhour.com/#/projects/ev:207615427437395(view:ev:208252969548104)
=> Custom byline support

sites/cannabisequipmentnews.com/config/site.js
Container was import/exported to new Lynch Media GTM account
=> Update CEN GTM container ID

sites/cannabisequipmentnews.com/config/site.js, sites/designdevelopmenttoday.com/config/site.js, sites/foodmanufacturing.com/config/site.js, sites/ien.com/config/site.js, sites/impomag.com/config/site.js, sites/inddist.com/config/site.js, sites/manufacturing.net/config/site.js, sites/mbtmag.com/config/site.js
~I'm adding DNS entries for CEN now, will update config again once the domain is available.~ I typod the domain when testing :P
=> Update imgix domains

sites/cannabisequipmentnews.com/config/site.js
https://parameter1.freshdesk.com/a/tickets/44
=> Update CEN company name

sites/designdevelopmenttoday.com/server/styles/index.scss
[FD 558](https://parameter1.freshdesk.com/a/tickets/558)
=> Swap DDT theme to use light colors

sites/ien.com/config/navigation.js, sites/manufacturing.net/config/navigation.js
[FD](https://parameter1.freshdesk.com/a/tickets/570)
[Pivotal](https://www.pivotaltracker.com/n/projects/2467321)
=> Add Podcast to navigation

sites/cannabisequipmentnews.com/server/routes/content.js, sites/designdevelopmenttoday.com/server/routes/content.js, sites/foodmanufacturing.com/server/routes/content.js, sites/ien.com/server/routes/content.js, sites/impomag.com/server/routes/content.js, sites/inddist.com/server/routes/content.js, sites/manufacturing.net/server/routes/content.js, sites/manufacturing.net/server/routes/index.js, sites/manufacturing.net/server/routes/redirects.js, sites/mbtmag.com/server/routes/content.js
Ref: https://parameter1.atlassian.net/browse/HELP-17
=> Update content route regex, add MNET video 404

packages/shared/templates/website-section/video.marko
=> Update video page to use the default website section layout

sites/inddist.com/config/navigation.js
=> Update magazine subscription link in all locations

packages/shared/components/blocks/related-content.marko
=> Alter the related-content query to pull cross site

packages/shared/start-server.js
If a “normal” redirect isn’t found, attempt to get a `to` value from a “sister-site”
Requires `graphql-server` `v2.31.0` to be live
=> Attempt to find a redirect from another site

sites/cannabisequipmentnews.com/config/navigation.js
=> Update advertise link CEN

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, docker-compose.yml, sites/medicaldesigndevelopment.com/browser/.eslintrc.js, sites/medicaldesigndevelopment.com/browser/index.js, sites/medicaldesigndevelopment.com/config/core.js, sites/medicaldesigndevelopment.com/config/gam.js, sites/medicaldesigndevelopment.com/config/identity-x.js, sites/medicaldesigndevelopment.com/config/native-x.js, sites/medicaldesigndevelopment.com/config/navigation.js, sites/medicaldesigndevelopment.com/config/site.js, sites/medicaldesigndevelopment.com/config/social-links.js, sites/medicaldesigndevelopment.com/index.js, sites/medicaldesigndevelopment.com/newrelic.js, sites/medicaldesigndevelopment.com/package.json, sites/medicaldesigndevelopment.com/server/public/robots.txt, sites/medicaldesigndevelopment.com/server/routes/content.js, sites/medicaldesigndevelopment.com/server/routes/dynamic-page.js, sites/medicaldesigndevelopment.com/server/routes/home.js, sites/medicaldesigndevelopment.com/server/routes/index.js, sites/medicaldesigndevelopment.com/server/routes/search.js, sites/medicaldesigndevelopment.com/server/routes/website-section.js, sites/medicaldesigndevelopment.com/server/styles/index.scss, sites/medicaldesigndevelopment.com/server/templates/index.marko, yarn.lock
'Microsite' copied over from DDT (basic set up)
I have also created the site in Base as well as some sections.
=> Create new microsite MDD

lerna.json, packages/contact-us/package.json, packages/shared/package.json, sites/cannabisequipmentnews.com/package.json, sites/designdevelopmenttoday.com/package.json, sites/designdevelopmenttoday.com/server/styles/index.scss, sites/foodmanufacturing.com/package.json, sites/ien.com/package.json, sites/impomag.com/package.json, sites/inddist.com/package.json, sites/manufacturing.net/package.json, sites/mbtmag.com/package.json, sites/medicaldesigndevelopment.com/package.json
=> Update DDT footer text color (make legible)

sites/medicaldesigndevelopment.com/config/site.js
=> Change company footer to Lynch Media-MDD site

packages/shared/config/footer-brand-logos.js, sites/medicaldesigndevelopment.com/config/site.js
=> Update image src with correct imgix path

packages/shared/browser/floating-video-player.vue, packages/shared/components/elements/embed-code.marko, packages/shared/components/elements/video-player.marko, packages/shared/components/layouts/website-section/default.marko, sites/cannabisequipmentnews.com/config/site.js
=> Adjust styling, playlist ID and render logic for BrightCove floating player.

sites/medicaldesigndevelopment.com/config/navigation.js
=> Update ‘advertise’ link

packages/shared/components/elements/video-player.marko, sites/medicaldesigndevelopment.com/config/site.js
=> Add Brightcove player to MDD site.

packages/global/browser/floating-video-player.vue, packages/global/scss/components/_brightcove-player.scss
Update how the player css is set.
=> Fix & move brightcove player css into vue component

sites/cannabisequipmentnews.com/config/navigation.js
=> Create ‘Podcast’ section and add to CEN navigation

sites/inddist.com/config/navigation.js
=> Add New Products to navigation Industrial Distribution.

packages/shared/scss/components/_footer.scss
=> Force flex-wrap: wrap on footer priamry nav items on smaller screens

sites/global.designdevelopmenttoday.com/server/styles/index.scss
=> Port navigation font-family style to ddt-global site

packages/shared/templates/content/index.marko
=> Adjust display rules for whitepaper primary image.

sites/global.cannabisequipmentnews.com/config/gam.js, sites/global.designdevelopmenttoday.com/config/gam.js, sites/global.foodmanufacturing.com/config/gam.js, sites/global.ien.com/config/gam.js, sites/global.impomag.com/config/gam.js, sites/global.inddist.com/config/gam.js, sites/global.manufacturing.net/config/gam.js, sites/global.mbtmag.com/config/gam.js, sites/global.medicaldesigndevelopment.com/config/gam.js
@brandonbk, @Shinsina 
I took a stab at this one... updating the new ad placements Richele created for the re-launch (global sites)
https://docs.google.com/spreadsheets/d/1pfekg8Dm5Dk7Z-ovzhPVm5HUuyE79HnXwaPEQhbLq9Q/edit#gid=0
=> Update ad units for new theme

packages/global/templates/home.marko
=> Change ‘Videos’ to ‘Popular Videos’

docker-compose.yml, packages/global/components/site-header-custom.marko, packages/global/start-server.js, sites/global.cannabisequipmentnews.com/config/newsletter.js, sites/global.designdevelopmenttoday.com/config/newsletter.js, sites/global.foodmanufacturing.com/config/newsletter.js, sites/global.ien.com/config/newsletter.js, sites/global.impomag.com/config/newsletter.js, sites/global.inddist.com/config/newsletter.js, sites/global.manufacturing.net/config/newsletter.js, sites/global.mbtmag.com/config/newsletter.js, sites/global.medicaldesigndevelopment.com/config/newsletter.js
=> Config footer signup & disable newsletter middleware & pushdown toggle button

packages/global/components/layouts/content/default.marko
This will now display the date if there is only 1 author
=> Alter conditional logic for loading published date on content pages

sites/ien.com/config/magazine.js
=> Use the correct publicationId for IEN's magazine configuration

packages/global/components/layouts/website-section/contact-us.marko, packages/global/components/layouts/website-section/default.marko, packages/global/components/layouts/website-section/marko.json, packages/global/graphql/fragments/content-contact-us.js, packages/global/routes/contact-us.js, packages/global/routes/index.js, packages/global/routes/redirects.js, packages/global/scss/core.scss, packages/global/templates/website-section/contact-us.marko
Add /contact-us routing and layout override.
=> Add contact us section layout override and update routing.

sites/ien.com/config/navigation.js
=> Add Contact Us to menu IEN

packages/global/components/elements/video-player.marko
=> Use site configuration for Video Player component playlist + player id's

sites/cannabisequipmentnews.com/config/site.js
=> Enable and configure Brightcove player on CEN.

packages/global/components/document.marko, packages/global/package.json, yarn.lock
=> Upgrade p1-events package version & ensure brandKey & identityQueryBuilder function are set correctly.

packages/global/components/layouts/content/default.marko, packages/global/scss/core.scss
=> Display teasers on content pages

sites/inddist.com/config/navigation.js, sites/medicaldesigndevelopment.com/config/navigation.js
=> Fix wrong footer info links-ID

packages/global/templates/dynamic-page/index.marko
Update to remove loadmore from primary section & fix footer.
=> Update dynamic page layout to fix footer

sites/medicaldesigndevelopment.com/config/navigation.js
=> Add oncology & news to navigation & menu

packages/global/components/layouts/website-section/default.marko
This fixes the id: undefined error if nothing is scheduled to a section
=> add if check for featured.nodes && featured.nodes.length

packages/global/components/document.marko
Reverts parameter1/industrial-media-websites#274
=> Revert "Add ScrollMagic"

sites/designdevelopmenttoday.com/config/navigation.js, sites/foodmanufacturing.com/config/navigation.js, sites/ien.com/config/navigation.js, sites/impomag.com/config/navigation.js, sites/inddist.com/config/navigation.js, sites/manufacturing.net/config/navigation.js, sites/mbtmag.com/config/navigation.js
=> Add podcast signup link to all Industrial Media sites’ nav

yarn.lock
Missed as a part of https://github.com/parameter1/industrial-media-websites/pull/279
=> Rebuild yarn.lock file on new dependencies

sites/designdevelopmenttoday.com/config/site.js, sites/foodmanufacturing.com/config/site.js, sites/impomag.com/config/site.js, sites/inddist.com/config/site.js, sites/manufacturing.net/config/site.js, sites/mbtmag.com/config/site.js
=> Configure unique Brightcover playerId's for INDM sites

sites/inddist.com/config/navigation.js
=> Rearrange nav items and add ‘5 minutes with id’

packages/global/routes/dynamic-page.js, packages/global/routes/redirects.js
**Redirects: redirect the /contact-us to /page/contact-us**
=> Update /contact-us route to use /page/contact-us

packages/global/templates/formstack.marko
=> Add reveal add call to formstack page

sites/cannabisequipmentnews.com/config/site.js, sites/impomag.com/config/site.js, sites/inddist.com/config/site.js, sites/mbtmag.com/config/site.js, sites/medicaldesigndevelopment.com/config/site.js
=> Update site logos image calls to be .svg

sites/inddist.com/config/site.js
=> Use site playlistId for Brightcove player, INDDIST

packages/global/scss/core.scss
=> Adjust styling of list elements in-body

docker-compose.yml, packages/global/components/document.marko, packages/global/scss/_variables.scss, packages/global/scss/components/_node.scss, packages/global/scss/core.scss, sites/cannabisequipmentnews.com/package.json, sites/designdevelopmenttoday.com/package.json, sites/foodmanufacturing.com/package.json, sites/ien.com/package.json, sites/impomag.com/package.json, sites/inddist.com/package.json, sites/manufacturing.net/package.json, sites/mbtmag.com/package.json, sites/medicaldesigndevelopment.com/package.json
**[STAGING](https://github.com/parameter1/industrial-media-websites/pull/318)**
=> Initial critical|nonCritical css setup 

packages/global/components/elements/video-player.marko, sites/foodmanufacturing.com/config/site.js, sites/manufacturing.net/config/site.js
=> Update Brightcove playlists

packages/global/components/layouts/content/default.marko
=> Include contact title and addressable fields on contact pages

sites/mbtmag.com/config/navigation.js
=> Add Podcast to nav and menu, MBT

packages/global/components/layouts/content/default.marko
=> Remove website and title from contact pages

sites/ien.com/config/navigation.js
=> Abbreviate Artificial Intelligence to AI, IEN nav

packages/global/package.json, packages/global/routes/feed.js
For Manufacturing.net:
Response from [https://www.manufacturing.net/__rss/all-published-content.xml?input={"includeTaxonomyIds"%3A[3199135]}](https://www.manufacturing.net/__rss/all-published-content.xml?input=%7B%22includeTaxonomyIds%22%3A%5B3199135%5D%7D): 
Response from what is implemented at `/yahoo-finance-feed`
=> Setup custom route for Yahoo Finance Feeds

packages/global/routes/feed.js
=> Additional media attributes for Yahoo FInance Feed

packages/global/routes/feed.js
=> Remove author email for Yahoo Finance Feed

sites/mbtmag.com/config/navigation.js
This should go live alongside a run of the script associated here: https://github.com/parameter1/base-scripts/pull/190
NOTE: Operations is temporarily omitted due to it being a brand new section with nothing presently populating it, should it be populated by the time this is ready to go, it should be re-added.
=> Update navigation with merged sections, MBT

packages/global/config/identity-x.js, sites/cannabisequipmentnews.com/config/identity-x.js, sites/designdevelopmenttoday.com/config/identity-x.js, sites/foodmanufacturing.com/config/identity-x.js, sites/ien.com/config/identity-x.js, sites/impomag.com/config/identity-x.js, sites/inddist.com/config/identity-x.js, sites/manufacturing.net/config/identity-x.js, sites/mbtmag.com/config/identity-x.js, sites/medicaldesigndevelopment.com/config/identity-x.js
=> Set/send primary_business & job_title to GTM

packages/global/components/layouts/content/default.marko, sites/cannabisequipmentnews.com/config/native-x.js, sites/designdevelopmenttoday.com/config/native-x.js, sites/foodmanufacturing.com/config/native-x.js, sites/ien.com/config/native-x.js, sites/impomag.com/config/native-x.js, sites/inddist.com/config/native-x.js, sites/manufacturing.net/config/native-x.js, sites/mbtmag.com/config/native-x.js, sites/medicaldesigndevelopment.com/config/native-x.js
=> Setup Section based Native ads (all sites)

sites/designdevelopmenttoday.com/config/native-x.js, sites/medicaldesigndevelopment.com/config/native-x.js
FORGOT ABOUT THE MINDFUL API (just needed to be patient)
=> Adjust MDD and DDT aliases for Native ads

packages/global/config/omeda-identity-x.js
=> Remove createFromIdentity override

packages/global/scss/components/content-meter.scss
=> Hide contentMeter messaging on submit of the form

sites/manufacturing.net/config/navigation.js
=> Add Gen Z to navigation

sites/cannabisequipmentnews.com/config/identity-x-opt-in-hooks.js
=> Add signup for CEN today onAuthenticationSuccess

sites/cannabisequipmentnews.com/config/social-links.js, sites/designdevelopmenttoday.com/config/social-links.js, sites/foodmanufacturing.com/config/social-links.js, sites/ien.com/config/social-links.js, sites/impomag.com/config/social-links.js, sites/inddist.com/config/social-links.js, sites/manufacturing.net/config/social-links.js, sites/mbtmag.com/config/social-links.js, sites/medicaldesigndevelopment.com/config/social-links.js
**I also adjusted all social links to open in a new tab, let me know if that was intentional to stay on the same page and I'll revert**
=> Add LinkedIn on MDD

sites/manufacturing.net/config/identity-x.js, sites/mbtmag.com/config/identity-x.js
=> Add subscription question for OT Security Update to actives MBT, MNET

packages/global/components/layouts/content/default.marko, packages/global/config/gam.js, sites/ien.com/config/gam.js
=> Create video ad slot

packages/global/templates/formstack.marko
=> Include inline style tag for correcting Formstack forms

sites/inddist.com/server/routes/home.js, sites/inddist.com/server/templates/home.marko
=> Adjust home page right rail to pull in 'Top News'

sites/foodmanufacturing.com/server/routes/home.js, sites/foodmanufacturing.com/server/templates/home.marko, sites/medicaldesigndevelopment.com/server/routes/home.js, sites/medicaldesigndevelopment.com/server/templates/home.marko
=> Adjust homepage top stories block

sites/manufacturing.net/config/navigation.js
=> Restore nav and move ‘Since 1998’ link to secondary nav

packages/global/templates/formstack.marko
=> Allow the form to fill the whole container on mobile
