sites/foodmanufacturing/server/templates/index.marko, sites/foodmanufacturing/server/templates/website-section/index.marko, sites/impomag/server/templates/index.marko, sites/impomag/server/templates/website-section/index.marko, sites/inddist/server/templates/index.marko, sites/inddist/server/templates/website-section/index.marko, sites/manufacturing/server/templates/index.marko, sites/manufacturing/server/templates/website-section/index.marko, sites/mbtmag/server/templates/index.marko, sites/mbtmag/server/templates/website-section/index.marko
Prevents a double page view fire, as the load more was immediately firing after the hero block.
=> Insert flow before load more on home and section pages

sites/foodmanufacturing/config/gam.js, sites/foodmanufacturing/server/styles/index.scss, sites/foodmanufacturing/server/templates/content/index.marko, sites/impomag/config/gam.js, sites/impomag/server/styles/index.scss, sites/impomag/server/templates/content/index.marko, sites/inddist/config/gam.js, sites/inddist/server/styles/index.scss, sites/inddist/server/templates/content/index.marko, sites/manufacturing/config/gam.js, sites/manufacturing/server/styles/index.scss, sites/manufacturing/server/templates/content/index.marko, sites/mbtmag/config/gam.js, sites/mbtmag/server/styles/index.scss, sites/mbtmag/server/templates/content/index.marko
Add billboard ad position to non-video content pages between the article body and load more.
Verified on on sites by including new ad units in an IEN placement, which has since been removed.
**Screenshots:**
=> INDM Billboard ads

sites/foodmanufacturing.com/config/navigation.js, sites/foodmanufacturing.com/server/templates/subscribe/index.marko, sites/impomag.com/config/navigation.js, sites/impomag.com/server/templates/subscribe/index.marko, sites/inddist.com/server/templates/subscribe/index.marko, sites/manufacturing.net/config/navigation.js, sites/manufacturing.net/server/templates/subscribe/index.marko, sites/mbtmag.com/config/navigation.js, sites/mbtmag.com/server/templates/subscribe/index.marko
- Remove the Magazine block from `/subscribe`
- Change the secondary "Subscribe" nav link to point to the appropriate Wufoo form
[Original Jira Request](https://southcomm.atlassian.net/browse/BCMS-215?atlOrigin=eyJpIjoiMzAxZWM1NzMzMzU3NDNmYjkxNjQ2NDY0MDEwZjZhNWEiLCJwIjoiaiJ9)
=> Remove magazines from subscribe page and redirect link to wufoo forms

packages/common/scss/shared.scss, sites/foodmanufacturing.com/server/styles/index.scss, sites/impomag.com/server/styles/index.scss, sites/inddist.com/server/styles/index.scss, sites/manufacturing.net/server/styles/index.scss, sites/mbtmag.com/server/styles/index.scss
Increase the bottom margin on primary videos. Example: https://www.manufacturing.net/home/video/21108724/company-hands-out-10-million-in-bonuses
Current:
Corrected/New:
[Original Jira Request](https://southcomm.atlassian.net/browse/BCMS-268?atlOrigin=eyJpIjoiNjc1NmJlOTQ5NjgxNDM2YWE1YmJlNmVjOTRkYjQwZjQiLCJwIjoiaiJ9)
=> Add bottom margin to content videos

packages/shared/scss/components/_node.scss
=> Increase teaser max height to prevent text cutoff

packages/shared/components/document.marko, packages/shared/components/marko.json, packages/shared/components/site-footer.marko, packages/shared/config/footer-brand-logos.js, packages/shared/config/footer-logos.js, packages/shared/scss/components/_footer.scss, packages/shared/scss/core.scss, sites/designdevelopmenttoday.com/config/site.js, sites/foodmanufacturing.com/config/site.js, sites/ien.com/config/site.js, sites/impomag.com/config/site.js, sites/inddist.com/config/site.js, sites/manufacturing.net/config/site.js, sites/mbtmag.com/config/site.js
Add shared footer-logos.js config to shared theme.  This is an array of logo objects.
**Example:**
```javascript
{
href: 'https://www.foodmanufacturing.com',
alt: 'Visit Food Manufacturing',
src: 'https://img.foodmanufacturing.com/files/base/indm/all/fm_logo.png?h=60',
srcset: [
'https://img.foodmanufacturing.com/files/base/indm/all/fm_logo.png?h=120 2x',
],
},
```
This is then pulled in and set on the individual site config under the logos.footer.brandLogos.  Added logic to site footer, so if brandLogos has logo objects in it, to loop over the array and it will display the logo and link to the other brands. Instead of just displaying the footer logo.
=> Add Logos/Links to all brand in footer of all sites except CEN

Dockerfile, services/marketing-cloud/Dockerfile
Updates 10.15 versions that were missed in #129. Fixes build errors due to version mismatch for marketing cloud service
=> Update node versions to 10.24

packages/shared/components/document.marko, packages/shared/components/elements/embed-code.marko, packages/shared/middleware/leads.js, packages/shared/start-server.js
Parses Leads identities and sets cookies server-side. Additionally, when present, pass the identifiers to Brightcove.
=> Server-side Leads identity cookie handling + video tracking

docker-compose.yml, packages/shared/browser/index.js, packages/shared/browser/omeda-incd.js, packages/shared/browser/omeda-lynchm.js, packages/shared/components/document.marko, packages/shared/components/layouts/website-section/default.marko, packages/shared/config/incd-omeda.js, packages/shared/config/lynchm-omeda.js, packages/shared/config/omeda.js, packages/shared/package.json, packages/shared/start-server.js, packages/shared/templates/content/index.marko, packages/shared/templates/dynamic-page/index.marko, sites/cannabisequipmentnews.com/browser/index.js, sites/cannabisequipmentnews.com/config/site.js, sites/designdevelopmenttoday.com/browser/index.js, sites/designdevelopmenttoday.com/config/site.js, sites/foodmanufacturing.com/browser/index.js, sites/foodmanufacturing.com/config/site.js, sites/ien.com/browser/index.js, sites/ien.com/config/site.js, sites/impomag.com/browser/index.js, sites/impomag.com/config/site.js, sites/inddist.com/browser/index.js, sites/inddist.com/config/site.js, sites/manufacturing.net/browser/index.js, sites/manufacturing.net/config/site.js, sites/mbtmag.com/browser/index.js, sites/mbtmag.com/config/site.js, yarn.lock
- Add deferred script loading for P1events & olytics (**@todo: update gtm tag for defered script loading of olytics**)
- Set omedaConfig to global from siteConfig to allow for brandIds & productIds
- Setup a lynchm & incd version of the rapidIdentiry vue component per brand and include on the site based on which brand they belong to.
=> Add P1 event tracking & omeda rapid identifier

packages/shared/components/document.marko, packages/shared/config/incd-omeda.js, packages/shared/config/lynchm-omeda.js
Add support and set the Omeda Olytics OID based on lynch media vs incd
**Screen shot of CEN vs IEN**
=> Add support for multiple Omeda Olytics OID

packages/shared/start-server.js
Redirects have been set from the previous alias of /newsletter-signup to the respective link for each site.
=> Allow redirection of subscribe links via database.

packages/shared/scss/components/_page.scss
=> Adjust justifcation of bullet points in content.

packages/shared/leads-content-handler.js
Prevents error when attempting to send a non-url-safe value as part of a header value.
=> Ensure company name header is URL safe

packages/shared/browser/floating-video-player.vue, packages/shared/browser/index.js, packages/shared/components/elements/video-player.marko, packages/shared/components/layouts/published-content.marko, packages/shared/components/layouts/website-section/default.marko, packages/shared/components/marko.json, packages/shared/package.json, packages/shared/templates/content/index.marko, packages/shared/templates/dynamic-page/index.marko, yarn.lock
Adds a custom Vue component utilizing the Brightcove player API to render a custom player on all non-video pages.
Standard page load
Scrolling down into push-up ad
=> Add bc floating player

packages/shared/scss/components/_page.scss
=> Reduce margin-right on mobile for byline items.

packages/shared/scss/core.scss
=> Correct CSS targeting for overlay elements, BrightCove Player.

packages/global/browser/floating-video-player.vue, packages/global/components/document.marko, packages/global/components/site-menu/index.marko, packages/global/config/identity-x-nav.js, packages/global/scss/components/_ads.scss, packages/global/scss/components/_site-navbar.scss, packages/global/start-server.js, packages/global/templates/user/authenticate.marko, packages/global/templates/user/login.marko, packages/global/templates/user/logout.marko, packages/global/templates/user/profile.marko, packages/global/templates/user/register.marko, sites/global.ien.com/config/navigation.js, sites/global.ien.com/config/site.js
Update toggle menu to be three column on desktop with Topics, Resources & User Tools.
I adjusted the right column to pull navigation.users.items, the social follow box and then navigation.toggleMenu.rightColumn.items.
**@TODO:** determine if the social follow menu css should stay in global or move to IEN site specifically.
=> Update global site toggle menu & add identity x navigation

packages/global/components/blocks/load-more/content-page.marko, packages/global/components/flows/content/card-deck.marko, packages/global/components/layouts/content/wrapper.marko, packages/global/components/layouts/website-section/default.marko
Increase the limit on load more to better match page size on current site with 6 rows of content.
=> Adjust loadmore call to display 15 items with 3 300x250 ads injected

packages/global/browser/floating-video-player.vue
Add an intersection Observer to play/pause the floating video player when scrolling it on/off screen.  Set the autoplay option on load to false.  This allows the new observer to determine if it is inView before triggering the start of the view.
=> add IntersectionObserver for floating video comp.

sites/cannabisequipmentnews.com/config/navigation.js, sites/designdevelopmenttoday.com/config/navigation.js, sites/foodmanufacturing.com/config/navigation.js, sites/ien.com/config/navigation.js, sites/impomag.com/config/navigation.js, sites/inddist.com/config/navigation.js, sites/manufacturing.net/config/navigation.js, sites/mbtmag.com/config/navigation.js, sites/medicaldesigndevelopment.com/config/navigation.js
If 'Video' was in Secondary, add to 'Resources' as well for consistency across the board
on ID: 'Big 50' is moved to 'Topics' in hamburger menu
64623209/186719408-65d69f94-9fd4-4a20-abe6-2afa029defd8.png">
=> Rearrange navigation and menu items

packages/global/scss/components/_content-page.scss
Make the styling for primary & imbedded images match.
=> Adjust how caption/credit displays on content pages

packages/global/scss/components/_node.scss, packages/global/scss/core.scss
=> Lower opacity of video icons, non-hero video items.

sites/inddist.com/config/navigation.js
=> Replace ‘Workforce’ & ‘Big 50’ in primary nav

packages/global/components/layouts/content/company-details.marko
=> Correct Website spelling, only display respective fields if populated on Company pages.

packages/global/components/layouts/dynamic-page/index.marko, packages/global/components/layouts/dynamic-page/marko.json, packages/global/components/layouts/marko.json, packages/global/routes/dynamic-page.js, packages/global/templates/dynamic-page/contact-us.marko, packages/global/templates/dynamic-page/index.marko, sites/cannabisequipmentnews.com/config/site.js, sites/designdevelopmenttoday.com/config/site.js, sites/foodmanufacturing.com/config/site.js, sites/ien.com/config/site.js, sites/impomag.com/config/site.js, sites/inddist.com/config/site.js, sites/manufacturing.net/config/site.js, sites/mbtmag.com/config/site.js, sites/medicaldesigndevelopment.com/config/site.js
dynamic pages have no form in right rail:
/page/contact-us will show form with updated title (**requires [base-cms PR](https://github.com/parameter1/base-cms/pull/468)**): https://github.com/parameter1/industrial-media-websites/pull/279:
/page/contact-us will show default title 'Drop us a line!') if one isn't provided:
=> Update dynamic pages & create unique contact-us page

packages/global/routes/index.js, packages/global/templates/formstack.marko
The new route will take /formstack/${lowercase-version-spaces-to-_-form-name}
**FormStack: shared path:** `https://ien.formstack.com/forms/making_the_culture_changes_that_assure_digital_transformation_success?utm_source=Industrial+Media&utm_medium=email&utm_campaign=02022023&utm_term=IMCD230201020&name-first=Jenna&name-last=Hulbert&email=jenna%40ien.com&phone_number=6087928007&nomodernizr=1&no_style_strict=1`
**Website Version:**
`https://www.ien.com/formstack/making_the_culture_changes_that_assure_digital_transformation_success?utm_source=Industrial+Media&utm_medium=email&utm_campaign=02022023&utm_term=IMCD230201020&name-first=Jenna&name-last=Hulbert&email=jenna%40ien.com&phone_number=6087928007&nomodernizr=1&no_style_strict=1`
**Example Form url parts**: …
=> Add simple route/template for loading formstack forms

packages/global/scss/core.scss
These css classes are referenced above the fold on magazine pages.
=> Make breadcrumbs & section-feeds css critical on mag routes

packages/global/components/layouts/content/default.marko
Open for discussion, essentially the `theme-read-next-block` uses an `all-published-content` query for the primary section of the content with the only exclusion being the content id you're looking at, this means for the home section (where everything lives for a site if unassigned anywhere else which will mostly be things like promotions, documents etc.) will display if it is the most recent item with that primary section (hence the Jenna dilemma), an alternative here would be allowing for passing in of `excludeContentTypes` to the `theme-read-next-block` which could remove things like pages, documents, etc. from that query and still present a read next block for other items with home as the primary section.
PROD:
DEV:
=> Remove read next block when primary section = Home

packages/global/components/layouts/dynamic-page/index.marko, packages/global/scss/core.scss
Text styling is now 'initial' if 2 lines:
Updated 'page' layout:
If right rail... no change:
=> Adjust 'Page' content type layout

sites/ien.com/config/identity-x.js
This was removed via: https://github.com/parameter1/industrial-media-websites/commit/14a8a837cdba9c2be6f29d203c1da60a895ec92c#diff-66c8d036b2ca99aa6eaa8b324b779c762be7618c8abb720de274a06841867a07L4 as part of https://github.com/parameter1/industrial-media-websites/pull/356
=> Re-enable commenting on IEN

sites/ien.com/config/site.js
Appears a recent PR here: https://github.com/parameter1/industrial-media-websites/pull/359
Conflicted with how IEN had been setup to handle these via: https://github.com/parameter1/industrial-media-websites/pull/211
This should now function identically across all sites.
=> Remove `idxNavItems` enablement, IEN

packages/global/browser/brightcove-gam-player.vue
Check to see that at least one of  bcVideoId || bcPlaylistId are set and use videoId with a fallback of playlistId
When both are set you will get a data conflict error when using the brightcovePlayerLoader() call.
=> Add videoId || videoPlaylistId brighrtcove fallback logic

packages/global/browser/brightcove-gam-player.vue
Add the appending and rendering of the impression tracker for gam
per https://support.google.com/admanager/answer/6088046?hl=en  It will now appending the required impression tracking <img />
=> Append gam tracker for impression tracking of brightcove ad

packages/global/components/blocks/load-more/content-page.marko, packages/global/components/layouts/content/wrapper.marko, packages/global/components/layouts/website-section/default.marko, sites/designdevelopmenttoday.com/config/native-x.js, sites/foodmanufacturing.com/config/native-x.js, sites/inddist.com/config/native-x.js, sites/manufacturing.net/config/native-x.js
=> Change section based nativeX ad slots to use 'Related Content' vs Default

packages/global/components/layouts/content/default.marko
Content ID Example: 22909409
On Page Load:
When Button is clicked (where you're jumped to), functions as it does now:
=> Utilize button to show Transcript when clicked

sites/foodmanufacturing.com/config/navigation.js, sites/ien.com/config/navigation.js, sites/impomag.com/config/navigation.js, sites/inddist.com/config/navigation.js, sites/manufacturing.net/config/navigation.js
=> Add ‘Since (year)’ to secondary nav
